project:
  type: website
  output-dir: ISV

website:
  title: "Inês S. Veríssimo"
  #site-path: "/inesverissimo/"
  description: "Data Scientist | Biomedical Engineer"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: docs/index.html
        text: CV
      - href: projects/projects.qmd
        text: Projects
      #- about.qmd

format:
  html:
    theme: 
      - lux #minty #
      - custom.scss
    css: styles.css
    #navbarcolor: "#4d9488"
    toc: true
    aliases: 
      - inesverissimo.html